### **5. Array Manipulation**

NumPy provides powerful functions to manipulate arrays, such as changing their shape, stacking, splitting, or repeating elements.

#### **Flatten Arrays**
- **`ravel()`**: Returns a flattened (1D) view of the array if possible, otherwise a copy. Modifying the result may affect the original array if it's a view.
- **`flatten()`**: Always returns a flattened copy, so modifications don’t affect the original array.


In [1]:
import numpy as np

arr=np.random.randint(0,100,size=(3,2,5))
print(np.shape(arr))
print(arr)

(3, 2, 5)
[[[88 21 22 85 18]
  [19 34 44 96 82]]

 [[99 30 50 42 47]
  [92 64  5 44 22]]

 [[ 3  3 79 77 58]
  [77 70 29 81 50]]]


In [2]:
arrFlat=arr.flatten()
print(arrFlat)


[88 21 22 85 18 19 34 44 96 82 99 30 50 42 47 92 64  5 44 22  3  3 79 77
 58 77 70 29 81 50]


In [3]:
arrReval=arr.ravel()
print(arrReval)

[88 21 22 85 18 19 34 44 96 82 99 30 50 42 47 92 64  5 44 22  3  3 79 77
 58 77 70 29 81 50]


In [8]:
arr[0][0][0]=0
print(arrFlat[0]) #This returns copy


88


In [9]:
arr[0][0][0]=0
print(arrReval[0]) #This returns view

0


#### **Expand Dimensions**
- **`np.expand_dims(arr, axis)`**: Adds a new axis at the specified position, increasing the array's dimensionality (e.g., 1D → 2D).
- Useful for preparing arrays for operations requiring specific shapes.

In [14]:
arr = np.array([1, 2, 3])  # Shape: (3,)
expanded = np.expand_dims(arr,axis=0)  # Add axis at index 0
print("Expanded (axis=0):\n", expanded,"\nShape: ", expanded.shape)  # [[1, 2, 3]], (1, 3)

expanded = np.expand_dims(arr, axis=1)  # Add axis at index 1
print("Expanded (axis=1):\n", expanded,"\nShape: ", expanded.shape)


Expanded (axis=0):
 [[1 2 3]] 
Shape:  (1, 3)
Expanded (axis=1):
 [[1]
 [2]
 [3]] 
Shape:  (3, 1)


#### **Squeeze Dimensions**
- **`np.squeeze(arr)`**: Removes axes of length 1 from the array, reducing dimensionality.
- Useful for cleaning up unnecessary dimensions.


In [15]:
arr = np.array([[[1, 2, 3]]])  # Shape: (1, 1, 3)
squeezed = np.squeeze(arr)
print("Squeezed:", squeezed, squeezed.shape)  # [1, 2, 3], (3,)


Squeezed: [1 2 3] (3,)



#### **Repeat and Tile**
- **`np.repeat(arr, n)`**: Repeats each element `n` times along the specified axis.
- **`np.tile(arr, (m, n))`**: Repeats the entire array `m` times along the first axis and `n` times along the second axis.


In [30]:
arr=np.array([1,2,3])

#np.repeat
rep=np.repeat(arr,3)
print("Repeat:", rep, rep.shape)

print("arr",arr)
tiled = np.tile(arr,(2,1))
print("Tiled:","\n", tiled,"\nShape", tiled.shape)


Repeat: [1 1 1 2 2 2 3 3 3] (9,)
arr [1 2 3]
Tiled: 
 [[1 2 3]
 [1 2 3]] 
Shape (2, 3)
