# NumPy Cheat Sheet 2023
### **1. Creating Arrays Commands**

Arrays in NumPy are of fixed size and homogeneous in nature. They are faster and more efficient because they are written in C language and are stored in a continuous memory location which makes them easier to manipulate. NumPy arrays provide N-dimensional array objects that are used in linear algebra, Fourier Transformation, and random number capabilities. These array objects are much faster and more efficient than the Python Lists.

## 1. Creating One-Dimensional Arrays
NumPy one-dimensional arrays are linear arrays created from Python lists, tuples, or using the `fromiter()` function.

### Methods
- **From Python List**: `np.array([1, 2, 3, 4, 5])`
- **From Python Tuple**: `np.array((1, 2, 3, 4, 5))`
- **Using `fromiter()`**: `np.fromiter((a for a in range(8)), float)`


In [12]:
from random import random

#From Python List
import numpy as np

list=[1,5,6,8]
arr=np.array(list) #list
print(arr)

#From tuple
arr=np.array((1,2,3)) #tupple
print(arr)




[1 5 6 8]
[1 2 3]


[1 5 6 8]


array([1, 5, 6, 8])

1
5
6
8


In [7]:
import random
import math
[math.floor(random.random()*10+1) for _ in range(10)]

[6, 8, 5, 5, 7, 1, 7, 6, 7, 6]