## 1. Creating Arrays in NumPy

NumPy arrays (`ndarray`) are the core data structure in NumPy, used for efficient storage and manipulation of numerical data. Arrays can be created in various ways, depending on the desired structure, values, or distribution. Below, we explore the key methods for creating arrays: `np.array()`, `np.zeros()`, `np.ones()`, `np.full()`, `np.arange()`, `np.linspace()`, and random array generation methods (`np.random.rand()`, `np.random.randn()`, `np.random.randint()`).

### Prerequisites
- Ensure NumPy is installed: `pip install numpy`
- Import NumPy: `import numpy as np`

---

### 1. `np.array()` – Basic Array Creation

**Purpose**: Creates a NumPy array from a Python list, tuple, or other iterable.

**Syntax**:
```python
np.array(object, dtype=None)
```
- `object`: Input data (e.g., list, tuple, nested lists).
- `dtype`: Desired data type (e.g., `int`, `float`, `bool`). If not specified, NumPy infers the type.

**Key Features**:
- Converts Python lists/tuples into a NumPy array.
- Supports multi-dimensional arrays (e.g., 2D matrices) by passing nested lists.
- The resulting array has a fixed shape based on the input.


In [9]:
import numpy as np
from numpy import dtype

#1D Array
arr=np.array([1,2,3,4])

#2D Array
arrTwoD=np.array([
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]
                ])
#3D Array
arrThreeD=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [[1,2,3],
    [4,5,6]]
])

In [12]:
print("1D array")
print(arr)
print("\n2D array")
print(arrTwoD)
print("\n3D array")
print(arrThreeD)

1D array
[1 2 3 4]

2D array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D array
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
#Specific Dtype
arrFloat=np.array([1,2,3],dtype=float)
arrInt=np.array([1,2,3],dtype=int)
arrString=np.array([1,2,3],dtype=str)

In [15]:
print("Float array")
print(arrFloat)
print("Int array")
print(arrInt)
print("String array")
print(arrString)

Float array
[1. 2. 3.]
Int array
[1 2 3]
String array
['1' '2' '3']


**Use Cases**:
- Converting existing data (e.g., lists from data processing) to NumPy arrays for numerical operations.
- Creating arrays with specific data types for memory efficiency or compatibility.

---

### 2. `np.zeros()` – Array of Zeros

**Purpose**: Creates an array filled with zeros.

**Syntax**:
```python
np.zeros(shape, dtype=float)
```
- `shape`: Tuple or integer specifying the array’s dimensions (e.g., `(2, 3)` for a 2x3 array).
- `dtype`: Data type (default is `float64`).

**Key Features**:
- Useful for initializing arrays with zeros, often as placeholders.
- Supports multi-dimensional arrays.
- Memory-efficient for large arrays.

In [24]:
#1D Array
arr = np.zeros(5 ,dtype=int)

print("\n1D array")
print(arr)

print("\n2D array")

#2D Array
arr=np.zeros((3,5),dtype=int)
print(arr)


1D array
[0 0 0 0 0]

2D array
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


**Use Cases**:
- Initializing matrices for iterative algorithms (e.g., dynamic programming).
- Creating masks or placeholders in machine learning models.

---

### 3. `np.ones()` – Array of Ones

**Purpose**: Creates an array filled with ones.

**Syntax**:
```python
np.ones(shape, dtype=float)
```
- `shape`: Tuple or integer specifying the array’s dimensions.
- `dtype`: Data type (default is `float64`).

**Key Features**:
- Similar to `np.zeros()`, but fills the array with ones.
- Useful for initializing weights or scaling factors.


In [25]:
arr=np.ones((2,5),dtype=int)
print("\n2D array")
print(arr)


2D array
[[1 1 1 1 1]
 [1 1 1 1 1]]


**Use Cases**:
- Initializing arrays for matrix operations (e.g., identity-like matrices).
- Setting default values for algorithms requiring a starting point of 1.

---

### 4. `np.full()` – Array with a Specified Value

**Purpose**: Creates an array filled with a specified value.

**Syntax**:
```python
np.full(shape, fill_value, dtype=None)
```
- `shape`: Tuple or integer specifying the array’s dimensions.
- `fill_value`: Scalar value to fill the array.
- `dtype`: Data type (inferred from `fill_value` if not specified).

**Key Features**:
- Generalizes `np.zeros()` and `np.ones()` by allowing any constant value.
- Flexible for initializing arrays with custom values.


In [26]:
arr=np.full((3,5),5,dtype=str)
print("\n2D array")
print(arr)


2D array
[['5' '5' '5' '5' '5']
 ['5' '5' '5' '5' '5']
 ['5' '5' '5' '5' '5']]



**Use Cases**:
- Initializing arrays with a specific constant (e.g., bias terms in neural networks).
- Creating arrays for testing with uniform values.

---

### 5. `np.arange()` – Array with a Range of Values

**Purpose**: Creates a 1D array with evenly spaced values within a specified range.

**Syntax**:
```python
np.arange(start, stop, step, dtype=None)
```
- `start`: Starting value (inclusive, default is 0).
- `stop`: End value (exclusive).
- `step`: Spacing between values (default is 1).
- `dtype`: Data type (inferred if not specified).

**Key Features**:
- Similar to Python’s `range()`, but returns a NumPy array.
- Supports integer and floating-point steps.
- Always produces a 1D array.

In [36]:
print(np.arange(1,5,1,dtype=float)) #Supports only integer and floating-point steps.
print(np.arange(1,5,0.2,dtype=float))

[1. 2. 3. 4.]
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8]


**Use Cases**:
- Generating indices for loops or slicing.
- Creating sequences for plotting or simulations.

---

### 6. `np.linspace()` – Array with Evenly Spaced Values

**Purpose**: Creates a 1D array with a specified number of evenly spaced values over a range.

**Syntax**:
```python
np.linspace(start, stop, num=50, dtype=float)
```
- `start`: Starting value (inclusive).
- `stop`: End value (inclusive by default).
- `num`: Number of values to generate (default is 50).
- `dtype`: Data type (default is `float64`).

**Key Features**:
- Unlike `np.arange()`, which uses a step size, `np.linspace()` specifies the number of points.
- Useful for generating smooth sequences for plotting or interpolation.
- Includes the `stop` value by default (unlike `np.arange()`).



In [47]:
np.linspace(1,20,10,dtype=float)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [48]:
arr1 = np.linspace(0, 10, 5)
print(arr1)  # Output: [ 0.   2.5  5.   7.5 10. ]

# 3 values from 1 to 2
arr2 = np.linspace(1, 2, 3)
print(arr2)  # Output: [1.  1.5 2. ]

# Integer dtype
arr3 = np.linspace(0, 10, 6, dtype=int)
print(arr3)  # Output: [ 0  2  4  6  8 10]

[ 0.   2.5  5.   7.5 10. ]
[1.  1.5 2. ]
[ 0  2  4  6  8 10]


`np.linspace(start, stop, num)` generates **num evenly spaced values** between `start` and `stop` (inclusive).

---

### Formula:

If we want the $i^{th}$ element (where $i = 0, 1, 2, ..., num-1$):

$$
a_i = start + i \times \frac{(stop - start)}{(num - 1)}
$$

---

### Example 1

```python
arr1 = np.linspace(0, 10, 5)
```

Here:

* start = 0
* stop = 10
* num = 5

Step size = $\dfrac{10 - 0}{5 - 1} = \dfrac{10}{4} = 2.5$

So elements:

* $a_0 = 0 + 0 \times 2.5 = 0$
* $a_1 = 0 + 1 \times 2.5 = 2.5$
* $a_2 = 0 + 2 \times 2.5 = 5$
* $a_3 = 0 + 3 \times 2.5 = 7.5$
* $a_4 = 0 + 4 \times 2.5 = 10$

✅ Output: `[0.  2.5  5.  7.5  10.]`

---

### Example 2

```python
arr2 = np.linspace(1, 2, 3)
```

Step size = $(2 - 1) / (3 - 1) = 0.5$

So: `[1.0, 1.5, 2.0]`

---

### Example 3

```python
arr3 = np.linspace(0, 10, 6, dtype=int)
```

* Step size = $(10 - 0) / (6 - 1) = 2$
* Values before dtype conversion: `[0, 2, 4, 6, 8, 10]`
* Since `dtype=int`, they are cast to integers → `[0, 2, 4, 6, 8, 10]`

---

👉 So the general **formula** is:

$$
a_i = \text{start} + i \cdot \frac{(\text{stop} - \text{start})}{(\text{num} - 1)}, \quad 0 \leq i < num
$$

---


**Use Cases**:
- Generating points for plotting functions (e.g., x-axis values).
- Creating evenly spaced samples for numerical analysis.

---

### 7. Random Arrays

NumPy’s `np.random` module provides functions to generate arrays with random values, useful for simulations, testing, or initializing machine learning models. Below are the key methods:

#### a. `np.random.rand()` – Uniform Distribution

**Purpose**: Generates random values from a uniform distribution over `[0, 1)`.

**Syntax**:
```python
np.random.rand(d0, d1, ..., dn)
```
- `d0, d1, ..., dn`: Dimensions of the output array (e.g., `(2, 3)` for a 2x3 array).
- Returns values in the range `[0, 1)`.

**Key Features**:
- Uniform distribution: each value is equally likely.
- Output is always a float in `[0, 1)`.


In [63]:
arr=np.random.rand(2,4)*50+1
print(arr)

[[43.57192312 40.21936167 23.53081731 12.90342743]
 [10.0781785  19.30314689 30.21712354 49.42528049]]


**Use Cases**:
- Generating random weights for neural networks.
- Simulating random processes with uniform probabilities.
---

#### b. `np.random.randn()` – Normal Distribution

**Purpose**: Generates random values from a standard normal (Gaussian) distribution (mean = 0, standard deviation = 1).

**Syntax**:
```python
np.random.randn(d0, d1, ..., dn)
```
- `d0, d1, ..., dn`: Dimensions of the output array.
- Returns values from a standard normal distribution.

**Key Features**:
- Values can be positive or negative, following a bell-shaped curve.
- Useful for statistical modeling or machine learning.


In [64]:
arr2 = np.random.randn(2, 2)
print(arr2)


[[ 1.47996295 -0.05208609]
 [ 0.90069118  0.42787009]]



**Use Cases**:
- Initializing weights in neural networks (normal distribution is common).
- Simulating noise or errors in data.

#### c. `np.random.randint()` – Random Integers

**Purpose**: Generates random integers within a specified range.

**Syntax**:
```python
np.random.randint(low, high=None, size=None, dtype=int)
```
- `low`: Lower bound (inclusive).
- `high`: Upper bound (exclusive). If `None`, assumes range is `[0, low)`.
- `size`: Shape of the output array (e.g., `(2, 3)` for a 2x3 array).
- `dtype`: Integer type (e.g., `int32`, `int64`).

**Key Features**:
- Generates integers, unlike `rand` or `randn`.
- Flexible for specifying array shape and range.



In [66]:
# 1D array of 5 random integers between 1 and 10
arr1 = np.random.randint(1, 10, size=5)
print(arr1)


[6 1 8 9 6]


In [70]:
# 2D array (2x3) with integers between 0 and 5
arr=np.random.randint(10,200,size=(3,5))
print(arr)

[[ 74 105 167  36  35]
 [144  61  93  63 142]
 [ 41  47  67 176 137]]


**Use Cases**:
- Generating random indices for sampling or shuffling.
- Simulating discrete random variables (e.g., dice rolls).

---

### Summary Table

| Method                  | Purpose                              | Key Parameters                       | Output Characteristics                  |
|-------------------------|--------------------------------------|--------------------------------------|-----------------------------------------|
| `np.array()`            | Create array from list/tuple         | `object`, `dtype`                    | Custom values, any shape                |
| `np.zeros()`            | Array of zeros                       | `shape`, `dtype`                     | All zeros, specified shape              |
| `np.ones()`             | Array of ones                        | `shape`, `dtype`                     | All ones, specified shape               |
| `np.full()`             | Array with custom value              | `shape`, `fill_value`, `dtype`       | All `fill_value`, specified shape       |
| `np.arange()`           | Sequence with fixed step             | `start`, `stop`, `step`, `dtype`     | 1D, evenly spaced, step-based           |
| `np.linspace()`         | Sequence with fixed number of points | `start`, `stop`, `num`, `dtype`      | 1D, evenly spaced, count-based          |
| `np.random.rand()`      | Uniform random values [0, 1)         | `d0, d1, ...`                        | Random floats, uniform distribution     |
| `np.random.randn()`     | Standard normal random values        | `d0, d1, ...`                        | Random floats, normal distribution      |
| `np.random.randint()`   | Random integers in range             | `low`, `high`, `size`, `dtype`       | Random integers, specified range/shape  |

---



### Additional Notes
- **Shapes**: For multi-dimensional arrays, specify shapes as tuples (e.g., `(2, 3)` for a 2x3 array).
- **Data Types**: Use `dtype` to control memory usage (e.g., `int8`, `float32`) or ensure compatibility with other libraries.
- **Random Seed**: To make random arrays reproducible, set a seed with `np.random.seed(seed_value)` before calling random functions.
  ```python
  np.random.seed(42)
  print(np.random.rand(3))  # Always produces the same random values
  ```
- **Performance**: NumPy arrays are faster and more memory-efficient than Python lists for numerical operations due to their fixed type and contiguous memory layout.

---