### **3. Array Attributes**

NumPy arrays have several attributes that provide metadata about the array's structure and content. These are essential for understanding and manipulating arrays effectively.

#### **Key Array Attributes**
1. **`shape`**: Returns a tuple representing the dimensions of the array (e.g., `(rows, columns)` for a 2D array).
2. **`size`**: Returns the total number of elements in the array (product of dimensions).
3. **`ndim`**: Returns the number of dimensions (axes) of the array.
4. **`dtype`**: Returns the data type of the array's elements (e.g., `int32`, `float64`).
5. **`itemsize`**: Returns the size (in bytes) of each element in the array.


In [3]:
import numpy as np
arr=np.array([1,2,3,4])

print("Shape: ",np.shape(arr))
print("Type: ",type(arr))
print("Value: ",arr)
print("dimention: ",np.ndim(arr))
print("size",np.size(arr)) #its = n*m
print("Data type: ",type(arr)," ",np.dtype(arr.dtype))
print("Itemize: ",arr.itemsize)
print("-------------------------")
print("Shape:", arr.shape)        # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)          # 6 → total elements (2 * 3)
print("Ndim:", arr.ndim)          # 2 → 2 dimensions
print("Dtype:", arr.dtype)        # int64 (or int32, depending on system)
print("Itemsize:", arr.itemsize)

Shape:  (4,)
Type:  <class 'numpy.ndarray'>
Value:  [1 2 3 4]
dimention:  1
size 4
Data type:  <class 'numpy.ndarray'>   int64
Itemize:  8
-------------------------
Shape: (4,)
Size: 4
Ndim: 1
Dtype: int64
Itemsize: 8


#### **Reshaping Arrays**
- The **`reshape()`** method changes the shape of an array without altering its data, but the total number of elements must remain the same.
- **Reshape Rule**: If the original shape has `a * b = x` elements, the new shape must satisfy `c * d = x`.
  - Example: A `(2, 3)` array (6 elements) can be reshaped to `(3, 2)`, `(1, 6)`, or `(6, 1)`, but not `(2, 4)` (as 2 * 4 = 8 ≠ 6).
- **Views vs. Copies**:
  - `reshape()` typically returns a **view** of the original array (not a copy), meaning changes to the reshaped array affect the original.
  - The `.base` attribute reveals whether an array is a view (points to the original array) or a copy (None).


In [9]:
arr=np.random.randint(1,100,size=(10))
print(arr)

[31 91 61 10 33 27 93 17 50 20]


In [15]:
arr=arr.reshape((2,5))
print(arr)

print("---------------")
#Back to original
arr=arr.base
print(arr)


[[31 91 61 10 33]
 [27 93 17 50 20]]
---------------
[31 91 61 10 33 27 93 17 50 20]


#### **Practice: Check `.base` After Reshape and Slicing**
- **Reshape**: As shown above, `reshape()` creates a view, so `.base` points to the original array.
- **Slicing**: Slicing an array also typically creates a view, not a copy.
- **Practice Task**: Verify if `.base` indicates a view after reshaping and slicing.

**Key Insight**: Both reshaping and slicing create **views** (`.base` points to the original array). To avoid modifying the original, use `.copy()`.

---

### **4. Indexing & Slicing**

NumPy supports powerful indexing and slicing mechanisms to access or modify array elements.

#### **Simple Indexing**
- Access elements using indices, similar to Python lists.
- Negative indices count from the end.

In [16]:
arr = np.array([10, 20, 30, 40])
print(arr[0])
print(arr[-1])

10
40


#### **2D Indexing**
- For 2D arrays, use `arr[row, col]` or `arr[row][col]`.
- Use `:` to select all elements along an axis.

In [17]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [28]:
print(arr[1,2])

6


In [29]:
print(arr[1:])

[[4 5 6]
 [7 8 9]]


In [32]:
print(arr[:2])

[[1 2 3]
 [4 5 6]]


#### **Fancy Indexing**
- Use lists or arrays of indices to select specific elements.
- Returns a **copy** (not a view).

In [33]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])

[10 30 50]


In [42]:
arr=np.array([[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

In [49]:
print(arr[[1,2],[0,1]])

[5 9]


### 🔎 What it means

* `arr[[1,2], [0,1]]`

  * The **first list** `[1,2]` gives the **row indices**
  * The **second list** `[0,1]` gives the **column indices**
  * NumPy pairs them **element by element** → it’s like zipping the indices.

So it selects:

* `arr[1, 0]` → element in row 1, column 0
* `arr[2, 1]` → element in row 2, column 1

And returns them as an array.

---

#### **Boolean Indexing**
- Use a boolean array to select elements that satisfy a condition.
- Returns a **copy** of elements where the condition is `True`.
- **Example**:

In [55]:
arr=np.array([[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print(arr[arr>5]) #it returns 1D array
print("--------------------------")
print(arr>5)

[6 7 8 9]
--------------------------
[[False False False]
 [False False  True]
 [ True  True  True]]


**Key Notes**:
- **Views vs. Copies**:
  - Slicing (e.g., `arr[1:3]`) creates a **view**.
  - Fancy and boolean indexing create a **copy**.
- **Boolean Indexing**: The condition generates a boolean array of the same shape, and elements where `True` are selected.

---

### **Summary of Key Points**
- **Array Attributes**: Use `shape`, `size`, `ndim`, `dtype`, and `itemsize` to inspect array properties.
- **Reshaping**: Use `reshape()` to change dimensions while preserving the total number of elements. Check `.base` to confirm if it’s a view.
- **Indexing & Slicing**:
  - Simple indexing: `arr[0]`, `arr[-1]`.
  - 2D indexing: `arr[row, col]`, `arr[:, col]`.
  - Fancy indexing: `arr[[indices]]` (copy).
  - Boolean indexing: `arr[condition]` (copy).
- **Practice Insight**: Reshaping and slicing create views (`.base` points to the original), while fancy and boolean indexing create copies (`.base` is `None`).

---

# NumPy Methods and Attributes Table

| Name | Type | Description | Example Usage |
|------|------|-------------|---------------|
| `shape` | Attribute | Returns a tuple representing the dimensions of the array (e.g., `(rows, columns)` for a 2D array). | `arr = np.array([1, 2, 3, 4])`<br>`print(arr.shape)` → `(4,)` |
| `size` | Attribute | Returns the total number of elements in the array (product of dimensions). | `arr = np.array([1, 2, 3, 4])`<br>`print(arr.size)` → `4` |
| `ndim` | Attribute | Returns the number of dimensions (axes) of the array. | `arr = np.array([1, 2, 3, 4])`<br>`print(arr.ndim)` → `1` |
| `dtype` | Attribute | Returns the data type of the array's elements (e.g., `int32`, `float64`). | `arr = np.array([1, 2, 3, 4])`<br>`print(arr.dtype)` → `int64` |
| `itemsize` | Attribute | Returns the size (in bytes) of each element in the array. | `arr = np.array([1, 2, 3, 4])`<br>`print(arr.itemsize)` → `8` |
| `base` | Attribute | Reveals whether an array is a view (points to the original array) or a copy (`None`). | `arr = np.random.randint(1, 100, size=(10))`<br>`arr_reshaped = arr.reshape((2, 5))`<br>`print(arr_reshaped.base)` → `[31 91 61 10 33 27 93 17 50 20]` |
| `np.array()` | Method | Creates a NumPy array from a list or other iterable. | `arr = np.array([10, 20, 30, 40])`<br>`print(arr)` → `[10 20 30 40]` |
| `np.shape()` | Method | Returns the shape of the array as a tuple (same as `arr.shape`). | `arr = np.array([1, 2, 3, 4])`<br>`print(np.shape(arr))` → `(4,)` |
| `np.ndim()` | Method | Returns the number of dimensions of the array (same as `arr.ndim`). | `arr = np.array([1, 2, 3, 4])`<br>`print(np.ndim(arr))` → `1` |
| `np.size()` | Method | Returns the total number of elements in the array (same as `arr.size`). | `arr = np.array([1, 2, 3, 4])`<br>`print(np.size(arr))` → `4` |
| `np.dtype()` | Method | Returns the data type of the array's elements (same as `arr.dtype`). | `arr = np.array([1, 2, 3, 4])`<br>`print(np.dtype(arr.dtype))` → `int64` |
| `np.random.randint()` | Method | Generates random integers within a specified range and shape. | `arr = np.random.randint(1, 100, size=(10))`<br>`print(arr)` → `[31 91 61 10 33 27 93 17 50 20]` |
| `reshape()` | Method | Changes the shape of an array without altering its data, preserving the total number of elements. Typically returns a view. | `arr = np.random.randint(1, 100, size=(10))`<br>`arr = arr.reshape((2, 5))`<br>`print(arr)` → `[[31 91 61 10 33] [27 93 17 50 20]]` |n

In [3]:
import numpy as np
arr=np.random.randint(1,200,(5,5))
arr

array([[100,   4,  69, 150,  87],
       [118, 169, 193,  88,   5],
       [176,  25,  98,  82,  63],
       [ 95, 120, 127, 166,  65],
       [ 43,  53, 186,  21,  62]], dtype=int32)

In [6]:
arr[[0,1],[2,1]]

array([ 69, 169], dtype=int32)